### ISSUE TITLE
Endpoint grouping/sorting is broken

### ISSUE THREAD

**Issue by jwineinger** [marcgibbons/django-rest-swagger#536] opened 2016-08-23 16:08 UTC
I just upgraded to the 2.x line and I don't seem to be able to get my docs back to anything similar to what I had with 0.3.5.  It appears that the new version groups endpoints based on the last path segment which is not variable. See the following screenshots:
![screen shot 2016-08-23 at 11 03 00 am](https://cloud.githubusercontent.com/assets/287161/17899596/6b544fe2-6921-11e6-9998-9e8ca9063984.png)
and 
![screen shot 2016-08-23 at 10 37 00 am](https://cloud.githubusercontent.com/assets/287161/17899600/6d8f9b86-6921-11e6-8de7-f19571a30444.png)

I would much rather have it grouped by all leading path segments which are not variable. So given the above screenshots, I would have the following groupings:
* /identity/orgs/
* /identity/v3/users/
* /identity/v2/users/
* /identity/users/
* /identity/apps/

**Comment by tawanda** [comment] 2016-08-23 18:58
I have the same issue +1

**Comment by duduklein** [comment] 2016-08-24 06:41
Did you try the [APIS_SORTER or OPERATIONS_SORTER](http://marcgibbons.github.io/django-rest-swagger/settings/#apis_sorter) settings?

Not sure if it helps, but I'm also discovering this new version

**Comment by tawanda** [comment] 2016-08-24 07:01
I personally tried both of those, 

APIS_SORTER -> arranges them alphabetically but not grouped correctly still

OPERATIONS_SORTER -> also an alphabetical sorter, or you can sort by http method, but if grouping is wrong it will be sorted wrong

before the update the grouping worked flawlessly

**Comment by jwineinger** [comment] 2016-08-24 15:00
Yes, I tried the APIS_SORTER. The grouping is still wrong.

**Comment by jwineinger** [comment] 2016-08-24 15:06
This might be caused by DRF. Looking at the XHR request to get the schemas, I see a "tags" array on each endpoint that matches the grouping that is being displayed.

django-rest-swagger could just use the path instead to fix this problem.

**Comment by marcgibbons** [comment] 2016-08-24 22:32
Correct. The grouping is rendered onto the CoreAPI document by the DRF SchemaGenerator (categories -> tags), while the sorting of the alphabetical sorting of tags can be turned on using the `APIS_SORTER: 'alpha' ` setting.

Similar to #515

**Comment by cmunk** [comment] 2016-09-29 11:26
So what is the solution? 

I have the following: 
![image](https://cloud.githubusercontent.com/assets/5957067/18951971/24c92d6a-8648-11e6-801d-554ff488b87c.png)

And it does not show "groups" or sorts in any meaningful way (see below for expanded view):
![image](https://cloud.githubusercontent.com/assets/5957067/18951988/3fef4c64-8648-11e6-89fa-e01a9cd64ec5.png)

How do I get my APIs grouped together? I have looked everywhere but can't figure it out. I am coming from previous version to 2.0.5

**Comment by tomchristie** [comment] 2016-09-30 14:55
The [upcoming 3.5 release of REST framework](https://github.com/tomchristie/django-rest-framework/pull/4525) has various improvements to the grouping used, and resolves this issue. Due to land sometime October 2016.

**Comment by angvp** [comment] 2016-10-21 04:54
I can confirm this issue is fixed, thanks @tomchristie

**Comment by angvp** [comment] 2016-10-26 22:05
@jwineinger try to update to 3.5 and let us know

@marcgibbons I think you can close this

**Closed** 2016-10-26 22:07 UTC
Labels: django-rest-framework
