### ISSUE TITLE
manytomany field in API Docs

### ISSUE THREAD

**Issue by mingot** [marcgibbons/django-rest-swagger#495] opened 2016-07-21 14:06 UTC
I am unable to create an object that has a manytomany field realtionship with django rest swagger. The reason is that it interprets a vector like [1,2] as a unicode object. Is there any workaround to it?

Thanks!

**Comment by marcgibbons** [comment] 2016-07-22 16:51
Hi @mingot - Django REST Framework is responsible for generating the schema and currently only supports strings. Please open an issue there.

**Comment by mingot** [comment] 2016-07-25 10:53
Hi @marcgibbons, 

Thanks for the response, but I am not sure I am understanding correctly. With Django REST framework I can create many to many fields and fill them with a POST request: 

`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"mymany2manyfield":[1,2]}' 'https://sampleapi.com'`

However when using the browsable autogenerated swagger API and entering in the swagger form field the many2manyfield value, it generates a POST requests that does not work (as it is using content-type `application/x-www-form-urlencoded` instead of `application/json`):

`curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json'  -d 'mymany2manyfield=%5B1%2C2%5D' 'https://sampleapi.com'`

Isn't it something that needs to be set in django-rest-swagger? How does people fill many2many fields using swagger browsable API?

Thanks again!

**Comment by marcgibbons** [comment] 2016-07-25 13:17
@mingot Sure.
The change in v2 of DRS is that Django REST Framework is now handling the introspection and schema generation while DRS is now focused on providing the renderer classes and customizations for the OpenAPI spec and SwaggerUI.

**Comment by tomchristie** [comment] 2016-08-11 10:45
Believe this to be a duplicate of #490 

Tracking this here: https://github.com/tomchristie/django-rest-framework/issues/4384

**Closed** 2016-08-11 21:32 UTC
Labels: django-rest-framework, duplicate
