### ISSUE TITLE
Add support for nested resources / URLs

### ISSUE THREAD

**Issue by j4nu5** [marcgibbons/django-rest-swagger#76] opened 2014-04-01 06:05 UTC
My API structure looks like:
/publications/
/publications/\<pubId\>/sections/
/publications/\<pubId\>/sections/\<secId\>/articles/
etc.

However, Swagger groups all of these under /publications/

Is there a workaround/proposal to fix this?

**Comment by grjones** [comment] 2015-01-28 16:52
+1 Since DRF doesn't support nested resources natively, is there a vision to support either `drf-nested-routers` or `drf-extensions`?

**Comment by maryokhin** [comment] 2015-01-28 21:30
+1 Vote for the `drf-extensions` nested routes.

**Comment by PhilipGarnero** [comment] 2015-03-24 20:18
+1 on this one.
I have an api inside an app and I don't want it to be at the top level url : 

    router = DefaultRouter()
    router.register(r'videos', VideoViewSet, base_name="video")
    router.register(r'teachers', TeacherViewSet, base_name="teacher")

    urlpatterns = patterns(
        '',
        ...
        url(r'^api/', include(router.urls)),
    )

The problem is that swagger is unpacking `videos` and `teachers` rendering everything under `api` ![current_rendering](https://cloud.githubusercontent.com/assets/5165169/6811852/3f285420-d26b-11e4-9adf-a621b6cdd859.png)

when I want to have a second level to keep things organized.
![expected_rendering](https://cloud.githubusercontent.com/assets/5165169/6811851/3f26d2ee-d26b-11e4-97e6-e00b59799bea.png)

**Comment by kisna72** [comment] 2015-11-19 19:00
@j4nu5 Did you find any workaround your problems? I am having the same issue.

**Comment by aadu** [comment] 2015-12-29 00:52
+1 -- running into the same issue.

**Comment by JonnyFunFun** [comment] 2016-01-25 19:53
+1, using `drf-extensions` as well

**Comment by vladimirnani** [comment] 2016-03-17 09:52
+1

**Comment by monk8800** [comment] 2016-03-17 11:20
+1 likewise using drf extensions

**Comment by marcgibbons** [comment] 2016-07-17 13:16
Closing this out - Schema generation is now coming from DRF.

**Closed by marcgibbons** 2016-07-17 13:16 UTC
